name: AutoCheck

on:
  workflow_dispatch:
  schedule:
    # 每天运行的时间, 这边会有8小时的时差, 北京时间比Github所使用时区快8个小时, 所以要设慢8个小时
    - cron:  '0 16,23 * * *'

jobs:
#the first job called healthcheck
  healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v2
        
        
      - name: Sync with upstream
        # 不是目标仓库则为fork的仓库, 且有设置 ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.repository != 'Freedomisgood/Zju_health_checkin_helper' }} 
        continue-on-error: true
        # 或者使用 uses: repo-sync/github-sync@v2
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          # 上游同步仓库
          upstream_sync_repo: Freedomisgood/Zju_health_checkin_helper
          # 上游同步分支
          upstream_sync_branch: main
          # 本地要保持同步的目标分支
          target_sync_branch: main
          # 本地要保持同步的目标仓库token, 即当前仓库
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_pull_args: "-s recursive -Xtheirs"

      - name: "Set python"
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: "Install pip"
        run: python3 -m pip install --upgrade pip
      - name: "install requirements"
        run: pip install -r requirements.txt

      - name: run the script
        env:
          account: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.PASSWORD }}
          campus: ${{ secrets.CAMPUS }}
          longitude: ${{ secrets.LONGITUDE }}
          latitude: ${{ secrets.LATITUDE }}
        # 如果嫌secrets填写麻烦, 下边的run可以改成 python main.py -a * -p * -lng 121.63529 -lat 29.89154 -c 宁波校区
        run: python3 main.py -a ${{ secrets.account }} -p ${{ secrets.password }} -lng ${{ secrets.longitude }} -lat ${{ secrets.latitude }} -c ${{ secrets.campus }}

#the second job called sendemail
  sendemail:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

        
      - name: 'Send email'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.MAIL_ACCOUNT }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: dingding check
          body: completed successfully!
          to: ${{ secrets.MAIL_TARGET }}
          from: github actions
    # only if job healthcheck complete successfully will send email.
    needs: healthcheck
